# Generated by Django 5.0.2 on 2024-03-09 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("link", models.CharField(max_length=300)),
                (
                    "date_pub",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="projects",
            name="image",
            field=models.ImageField(upload_to="./templates/static/portfolio/images"),
        ),
    ]
