# Generated by Django 5.0.2 on 2024-03-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_blogs_alter_projects_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="image",
        ),
        migrations.RemoveField(
            model_name="projects",
            name="technology",
        ),
        migrations.AddField(
            model_name="projects",
            name="link",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="link",
            field=models.CharField(max_length=50),
        ),
    ]
