# Generated by Django 5.0.2 on 2024-03-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_remove_projects_image_remove_projects_technology_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="link",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="projects",
            name="link",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
