# Generated by Django 5.0.2 on 2024-03-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_blogs_link_alter_projects_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="short_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="projects",
            name="image",
            field=models.ImageField(blank=True, upload_to="portfolio/images/"),
        ),
        migrations.AddField(
            model_name="projects",
            name="short_description",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
